version: '3.8'  

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy  
    environment:
      DATABASE_URL: "host=db user=postgres password=example dbname=postgres port=5432 sslmode=disable"
    ports:
      - "8081:8081"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:  
