apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 0 # Ensure at least one instance is running
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "example"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres  # Ensure the service name is 'postgres'
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
  type: ClusterIP
  

